# Generated by Django 4.0.8 on 2022-11-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_hodos',
        ),
    ]
