# Generated by Django 4.0.8 on 2023-01-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
