# Generated by Django 4.0.8 on 2022-10-18 19:29

from django.db import migrations, models
import search_route.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('url_image', models.ImageField(default='routes/default.jpg', upload_to=search_route.models.upload_to_routes, verbose_name='Image')),
            ],
            options={
                'db_table': 'route',
            },
        ),
    ]
