# Generated by Django 4.0.8 on 2023-02-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_route', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='url_image',
            new_name='image',
        ),
    ]
