# Generated by Django 4.0.8 on 2023-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_route', '0003_rename_url_image_route_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
