# Generated by Django 4.0.8 on 2023-02-24 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search_route', '0005_route_visited_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='avg_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=-1)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_route.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
