# Generated by Django 4.0.8 on 2022-10-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point_of_route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'point_of_route',
            },
        ),
    ]
