# Generated by Django 4.0.8 on 2022-10-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('point_of_route', '0001_initial'),
        ('search_route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_of_route',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_route.route'),
        ),
    ]
