# Generated by Django 4.0.8 on 2023-02-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_route', '0003_remove_point_of_route_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_of_route',
            name='index',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
